vich_uploader:
    db_driver: orm

    mappings:
        contract_image:
            uri_prefix: /images/contracts
            upload_destination: '%kernel.project_dir%/public/images/contracts'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
